#!/usr/bin/env sh

##
# Usage
#
# Open repo from remote url
# $ git open
#
# Open repo to current branch from remote url
# $ git open current
#
##

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ $1 = 'current' || $2 = 'current' ]]; then
  open $(git config --get remote.origin.url | sed -e 's/git@/https:\/\//' -e 's/github.com:/github.com\//' -e 's/.git$//' -e 's/$/\/tree\//')$BRANCH;
else
  echo $(git config --get remote.origin.url | sed -e 's/git@/https:\/\//' -e 's/github.com:/github.com\//' -e 's/.git$//')
fi